// <auto-generated />
using System;
using BlackSheepsOfAI.ParkAndRideYellowBus.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NetTopologySuite.Geometries;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BlackSheepsOfAI.ParkAndRideYellowBus.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260516112601_AddBusStopAndSchools")]
    partial class AddBusStopAndSchools
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "postgis");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BlackSheepsOfAI.ParkAndRideYellowBus.Core.Entities.BusStop", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Bus")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("bus");

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("geom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_bus_stop");

                    b.ToTable("bus_stop", (string)null);
                });

            modelBuilder.Entity("BlackSheepsOfAI.ParkAndRideYellowBus.Core.Entities.FormDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("Fields")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("fields");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("title");

                    b.Property<int>("Version")
                        .HasColumnType("integer")
                        .HasColumnName("version");

                    b.HasKey("Id")
                        .HasName("pk_form_definitions");

                    b.ToTable("form_definitions", (string)null);
                });

            modelBuilder.Entity("BlackSheepsOfAI.ParkAndRideYellowBus.Core.Entities.FormSubmission", b =>
                {
                    b.Property<Guid>("SubmissionId")
                        .HasColumnType("uuid")
                        .HasColumnName("submission_id");

                    b.Property<Guid>("FormId")
                        .HasColumnType("uuid")
                        .HasColumnName("form_id");

                    b.Property<int>("FormVersion")
                        .HasColumnType("integer")
                        .HasColumnName("form_version");

                    b.Property<DateTimeOffset>("SubmittedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("submitted_at");

                    b.Property<string>("Values")
                        .IsRequired()
                        .HasColumnType("jsonb")
                        .HasColumnName("values");

                    b.HasKey("SubmissionId")
                        .HasName("pk_form_submissions");

                    b.HasIndex("FormId")
                        .HasDatabaseName("ix_form_submissions_form_id");

                    b.ToTable("form_submissions", (string)null);
                });

            modelBuilder.Entity("BlackSheepsOfAI.ParkAndRideYellowBus.Core.Entities.School", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<Geometry>("Geom")
                        .IsRequired()
                        .HasColumnType("geometry")
                        .HasColumnName("geom");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("character varying")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_schools");

                    b.ToTable("schools", (string)null);
                });

            modelBuilder.Entity("BlackSheepsOfAI.ParkAndRideYellowBus.Core.Entities.FormSubmission", b =>
                {
                    b.HasOne("BlackSheepsOfAI.ParkAndRideYellowBus.Core.Entities.FormDefinition", null)
                        .WithMany()
                        .HasForeignKey("FormId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_form_submissions_form_definitions_form_id");
                });
#pragma warning restore 612, 618
        }
    }
}
