services:
  postgres:
    image: postgis/postgis:16-3.4
    container_name: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: pgadmin
    restart: unless-stopped
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
      - ./pgadmin-storage:/var/lib/pgadmin/storage/admin_admin.com
    depends_on:
      - postgres

  valhalla:
    image: ghcr.io/gis-ops/docker-valhalla/valhalla:latest
    platform: linux/amd64
    container_name: valhalla
    restart: unless-stopped
    ports:
      - "8002:8002"
    environment:
      - tile_urls=https://download.geofabrik.de/europe/croatia-latest.osm.pbf
      - serve_tiles=True
      - build_elevation=False
      - build_admins=True
      - build_time_zones=True
      - force_rebuild=False
    volumes:
      - valhalla_data:/custom_files

volumes:
  postgres_data:
  pgadmin_data:
  valhalla_data: